---
  - hosts: db
    become: yes
    tasks:
    - name: Install software packages
      yum:  name={{ item }} state=present
      with_items:
        - ntp
        - mariadb-server
        - MySQL-python
    - name: Ensure services are running.
      service: name={{ item }} state=started enabled=yes
      with_items:
        - ntpd
        - mariadb
