---
- hosts: app
  become: yes
  tasks:
  - name: Install software packages
    yum:  name={{ item }} state=present
    with_items:
      - ntp
      - MySQL-python
      - python-setuptools
  - name: Install django (not avail. via yum)
    easy_install: name=django
  - name: Ensure NTP is running.
    service: name=ntpd state=started enabled=yes
  - name: Create user groups
    group: name=admins state=present
  - name: Create user accounts
    user: name=pshanks state=present createhome=yes group=admins
